[package]
name = "anthropic-auth"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "anthropic-auth"
path = "src/bin/main.rs"

[dependencies]
thiserror = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }
sha2 = "0.10"
base64 = "0.22"
open = "5"
dirs = "5"
